### Import Libraries

In [2]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time


pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html


### Haarcascade import

In [3]:
mixer.init()
sound = mixer.Sound('alarm.wav')

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")
model = load_model(os.path.join("models", "model.h5"))

In [4]:
lbl=['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

### Real time Detection and Alarm horn

In [5]:
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
       #Condition for Close
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            #print("Close Eyes")
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            #print("Open Eyes")
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows() 

1/1 [==============================] - 1s 896ms/step
[[0.7840448  0.21595527]]
1/1 [==============================] - 0s 32ms/step
[[0.07458414 0.9254159 ]]
1/1 [==============================] - 0s 31ms/step
[[6.638283e-10 1.000000e+00]]
1/1 [==============================] - 0s 29ms/step
[[5.530758e-07 9.999994e-01]]
1/1 [==============================] - 0s 36ms/step
[[0.00222095 0.9977791 ]]
1/1 [==============================] - 0s 29ms/step
[[0.9582012  0.04179874]]
1/1 [==============================] - 0s 32ms/step
[[0.24322127 0.7567788 ]]
1/1 [==============================] - 0s 29ms/step
[[0.29266477 0.7073353 ]]
1/1 [==============================] - 0s 30ms/step
[[5.6552e-13 1.0000e+00]]
1/1 [==============================] - 0s 34ms/step
[[3.1070528e-04 9.9968934e-01]]
1/1 [==============================] - 0s 31ms/step
[[0.768343   0.23165704]]
1/1 [==============================] - 0s 33ms/step
[[0.50496066 0.4950394 ]]
1/1 [==============================] - 0s 32ms/st

[[0.06684718 0.9331528 ]]
1/1 [==============================] - 0s 32ms/step
[[0.5120186  0.48798135]]
1/1 [==============================] - 0s 30ms/step
[[0.3019218 0.6980782]]
1/1 [==============================] - 0s 26ms/step
[[4.3270137e-04 9.9956733e-01]]
1/1 [==============================] - 0s 28ms/step
[[3.6419335e-06 9.9999630e-01]]
1/1 [==============================] - 0s 27ms/step
[[9.704709e-12 1.000000e+00]]
1/1 [==============================] - 0s 26ms/step
[[0.93756145 0.06243854]]
1/1 [==============================] - 0s 30ms/step
[[0.00657829 0.99342173]]
1/1 [==============================] - 0s 30ms/step
[[0.8905129  0.10948718]]
1/1 [==============================] - 0s 30ms/step
[[0.6547738  0.34522626]]
1/1 [==============================] - 0s 27ms/step
[[6.447060e-08 9.999999e-01]]
1/1 [==============================] - 0s 30ms/step
[[3.1544475e-11 1.0000000e+00]]
1/1 [==============================] - 0s 26ms/step
[[0.5059282  0.49407175]]
1/1 [=========

KeyboardInterrupt: 